'use client';
import { use, useState } from 'react';
import Link from 'next/link';
import { Printer, Copy, CheckCircle2 } from 'lucide-react';
import { Badge, Loading, Notice, Shell, usePoll } from '@/components/ui';
import { formattedDate } from '@/lib/domain';
type TicketData = { code: string; name: string; serviceName: string; day: string; status: string; createdAt: string; counter?: string; ahead: number; isToday: boolean };
export default function TicketPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params); const { data, error, loading } = usePoll<TicketData>('tickets/' + token); const [message, setMessage] = useState('');
  return <Shell title="Tiket antrian Anda" subtitle="Status diperbarui otomatis. Simpan tautan ini untuk memeriksa kembali."><Notice>{error}</Notice>{loading && !data ? <Loading/> : data && <div className="ticket-wrap"><div className="ticket-success"><CheckCircle2/>Nomor antrian berhasil diterbitkan</div><article className="ticket-print card"><div className="ticket-top"><span className="eyebrow">ANTRIAN REGISTRASI IMEI</span><Badge status={data.status}/></div><div className="ticket-number">{data.code}</div><h2>{data.serviceName}</h2><div className="ticket-perforation"/><dl className="ticket-details"><div><dt>Nama pengunjung</dt><dd>{data.name}</dd></div><div><dt>Tanggal & waktu</dt><dd>{formattedDate(data.createdAt)} WIB</dd></div><div><dt>Loket</dt><dd>{data.counter || 'Menunggu panggilan'}</dd></div><div><dt>Antrian menunggu di depan</dt><dd>{data.ahead} orang <small>(layanan yang sama)</small></dd></div></dl>{!data.isToday && <Notice>Tiket ini berasal dari tanggal sebelumnya. Hubungi petugas jika belum terlayani.</Notice>}{data.status === 'CALLED' && <Notice success>Silakan menuju {data.counter}.</Notice>}{data.status === 'SKIPPED' && <Notice>Nomor Anda dilewati. Hubungi petugas untuk dipanggil kembali.</Notice>}<div className="ticket-token"><span>Kode akses pribadi</span><code>{token}</code></div><p className="ticket-foot">Harap menunggu hingga nomor Anda dipanggil.</p></article><div className="ticket-actions no-print"><button className="primary" onClick={() => window.print()}><Printer size={19}/>Cetak tiket</button><button className="secondary" onClick={async () => { try { await navigator.clipboard.writeText(window.location.href); setMessage('Tautan tiket berhasil disalin.'); } catch { setMessage('Salin tautan melalui kolom alamat browser.'); } }}><Copy size={18}/>Salin tautan</button></div><Notice success>{message}</Notice><Link className="text-link no-print" href="/">Kembali ke halaman utama</Link></div>}</Shell>;
}
