'use client';
import { useEffect, useRef, useState } from 'react';
import { Download, Plus, Pencil, Save, X, Users, Ticket, CheckCircle2, Clock3, Settings2 } from 'lucide-react';
import { api, Badge, Empty, Loading, Notice, Shell, Submit, usePoll } from '@/components/ui';
import { formattedDate, jakartaDay, statusLabels } from '@/lib/domain';
import type { AdminData, HistoryRow, Settings } from '@/lib/types';
type Tab = 'history' | 'settings' | 'users' | 'services' | 'counters';
type Edit = { id?: string; name: string; email?: string; role?: string; prefix?: string; active: boolean };
export default function AdminPage() {
  const { data, error, loading, refresh } = usePoll<AdminData>('admin/data', 10000);
  const [tab, setTab] = useState<Tab>('history'), [busy, setBusy] = useState(false), [failure, setFailure] = useState(''), [message, setMessage] = useState('');
  const [edit, setEdit] = useState<Edit | null>(null); const dialog = useRef<HTMLDialogElement>(null);
  const [day, setDay] = useState(jakartaDay()), [service, setService] = useState(''), [status, setStatus] = useState(''), [page, setPage] = useState(1);
  const query = new URLSearchParams({ day, ...(service ? { serviceId: service } : {}), ...(status ? { status } : {}), page: String(page) });
  const history = usePoll<{ rows: HistoryRow[]; total: number; page: number }>('admin/history?' + query, 15000);
  useEffect(() => { if (edit) dialog.current?.showModal(); else dialog.current?.close(); }, [edit]);
  async function save(path: string, value: unknown) {
    setBusy(true); setFailure(''); setMessage('');
    try { await api('admin/' + path, value); setMessage('Perubahan berhasil disimpan.'); setEdit(null); await refresh(); return true; }
    catch (e) { setFailure((e as Error).message); return false; }
    finally { setBusy(false); }
  }
  return <Shell title="Administrasi layanan" subtitle="Pantau pelayanan hari ini dan kelola pengaturan antrian." privatePage><Notice>{error}</Notice>{!edit && <Notice>{failure}</Notice>}<Notice success>{message}</Notice>{loading && !data ? <Loading/> : data && <>
    <div className="admin-stats">{[{ label: 'Total hari ini', count: Object.values(data.counts).reduce((a, b) => a + b, 0), icon: Ticket }, { label: 'Menunggu', count: data.counts.WAITING || 0, icon: Clock3 }, { label: 'Dipanggil', count: data.counts.CALLED || 0, icon: Users }, { label: 'Dilayani', count: data.counts.SERVING || 0, icon: Users }, { label: 'Selesai', count: data.counts.DONE || 0, icon: CheckCircle2 }, { label: 'Dilewati', count: data.counts.SKIPPED || 0, icon: Clock3 }].map(s => <div className="card admin-stat" key={s.label}><s.icon size={19}/><strong>{s.count}</strong><span>{s.label}</span></div>)}</div>
    <nav className="tabs" aria-label="Menu administrasi">{([['history', 'Riwayat antrian'], ['settings', 'Pengaturan'], ['users', 'Akun petugas'], ['services', 'Layanan'], ['counters', 'Loket']] as [Tab, string][]).map(([key, text]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => { setTab(key); setFailure(''); setMessage(''); }}>{text}</button>)}</nav>
    {tab === 'history' && <section className="card"><div className="section-title"><h2>Riwayat pelayanan</h2><a className="secondary compact" href={'/api/admin/export?' + query}><Download size={17}/>Ekspor CSV</a></div><div className="filters"><label className="field">Tanggal<input type="date" value={day} required onChange={e => { if (e.target.value) { setDay(e.target.value); setPage(1); } }}/></label><label className="field">Layanan<select value={service} onChange={e => { setService(e.target.value); setPage(1); }}><option value="">Semua layanan</option>{data.services.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Status<select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Semua status</option>{Object.entries(statusLabels).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label></div><Notice>{history.error}</Notice>{history.loading && !history.data ? <Loading/> : !history.data?.rows.length ? <Empty>Tidak ada antrian sesuai filter.</Empty> : <div className="table-scroll"><table><thead><tr><th>Nomor</th><th>Pengunjung</th><th>Layanan</th><th>Status</th><th>Loket</th><th>Catatan aktivitas</th></tr></thead><tbody>{history.data.rows.map(q => <tr key={q.id}><td><strong className="queue-code">{q.code}</strong><small>{formattedDate(q.createdAt)}</small></td><td>{q.name}<small>{q.phone || 'Tanpa nomor HP'}</small></td><td>{q.serviceName}</td><td><Badge status={q.status}/></td><td>{q.counter?.name || '—'}</td><td><details><summary>{q.events.length} aktivitas</summary><div className="event-list">{q.events.map(e => <div key={e.id}><strong>{e.action === 'CALL' ? 'Panggilan' : statusLabels[e.status]}</strong><span>{formattedDate(e.createdAt)} WIB</span><span>{e.user?.name || 'Pengunjung'}{e.counterName ? ` · ${e.counterName}` : ''}</span></div>)}</div></details></td></tr>)}</tbody></table></div>}<div className="pagination"><span>{history.data?.total || 0} antrian · Halaman {page}</span><div><button className="secondary compact" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Sebelumnya</button><button className="secondary compact" disabled={page * 30 >= (history.data?.total || 0)} onClick={() => setPage(p => p + 1)}>Berikutnya</button></div></div></section>}
    {tab === 'settings' && <SettingsForm initial={data.settings} busy={busy} onSave={value => save('settings', value)}/>}
    {['users', 'services', 'counters'].includes(tab) && <section className="card"><div className="section-title"><h2>{tab === 'users' ? 'Akun petugas dan admin' : tab === 'services' ? 'Jenis layanan' : 'Loket pelayanan'}</h2><button className="primary compact" onClick={() => { setFailure(''); setEdit({ name: '', active: true, ...(tab === 'users' ? { email: '', role: 'STAFF' } : {}), ...(tab === 'services' ? { prefix: '' } : {}) }); }}><Plus size={17}/>Tambah {tab === 'users' ? 'akun' : tab === 'services' ? 'layanan' : 'loket'}</button></div><p className="muted">Nonaktifkan data yang tidak digunakan. Riwayat pelayanan tetap tersimpan.</p><div className="table-scroll"><table><thead><tr><th>Nama</th><th>{tab === 'users' ? 'Email / Peran' : tab === 'services' ? 'Awalan nomor' : 'Status loket'}</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{((tab === 'users' ? data.users : tab === 'services' ? data.services : data.counters) as Edit[]).map(row => <tr key={row.id}><td><strong>{row.name}</strong></td><td>{'email' in row ? <>{row.email}<small>{row.role === 'ADMIN' ? 'Administrator' : 'Petugas'}</small></> : 'prefix' in row ? row.prefix : 'Loket pelayanan'}</td><td><span className={`badge ${row.active ? 'status-done' : 'status-skipped'}`}>{row.active ? 'Aktif' : 'Nonaktif'}</span></td><td><button className="secondary compact" onClick={() => { setFailure(''); setEdit({ ...row }); }}><Pencil size={15}/>Ubah</button></td></tr>)}</tbody></table></div></section>}
    <dialog ref={dialog} onCancel={() => { if (!busy) setEdit(null); }} className="edit-dialog"><div className="section-title"><h2>{edit?.id ? 'Ubah' : 'Tambah'} {tab === 'users' ? 'akun' : tab === 'services' ? 'layanan' : 'loket'}</h2><button className="icon-button" disabled={busy} onClick={() => setEdit(null)} aria-label="Tutup"><X/></button></div>{edit && <form key={edit.id || 'new'} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const active = form.get('active') === 'on'; if (edit.active && !active && !confirm(`Nonaktifkan ${edit.name}? Data tetap tersimpan dalam riwayat.`)) return; const value = { id: edit.id, name: form.get('name'), active, ...(tab === 'users' ? { email: form.get('email'), role: form.get('role'), ...(form.get('password') ? { password: form.get('password') } : {}) } : {}), ...(tab === 'services' ? { prefix: form.get('prefix') } : {}) }; void save(tab, value); }}><label className="field">Nama<input name="name" defaultValue={edit.name} required minLength={2} maxLength={100}/></label>{tab === 'users' && <><label className="field">Email<input type="email" name="email" defaultValue={edit.email} required/></label><label className="field">Peran<select name="role" defaultValue={edit.role}><option value="STAFF">Petugas</option><option value="ADMIN">Administrator</option></select></label><label className="field">Kata sandi {edit.id && <span className="optional">Kosongkan jika tetap</span>}<input name="password" type="password" required={!edit.id} minLength={12} maxLength={128} autoComplete="new-password" placeholder="Minimal 12 karakter"/></label></>}{tab === 'services' && <label className="field">Awalan nomor<input name="prefix" defaultValue={edit.prefix} required pattern="[A-Za-z]{1,3}" maxLength={3} placeholder="Contoh: R"/></label>}<label className="checkbox-field"><input type="checkbox" name="active" defaultChecked={edit.active}/>Aktif</label><Notice>{failure}</Notice><Submit busy={busy} className="primary full"><Save size={18}/>Simpan perubahan</Submit></form>}</dialog>
  </>}</Shell>;
}
function SettingsForm({ initial, busy, onSave }: { initial: Settings; busy: boolean; onSave: (value: Settings) => Promise<boolean> }) {
  return <section className="card settings-card"><div className="section-title"><h2>Identitas & jam pelayanan</h2><Settings2 size={22}/></div><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const enabled = form.get('enabled') === 'on'; if (initial.enabled && !enabled && !confirm('Tutup pengambilan nomor antrian? Petugas tetap dapat melayani antrian yang sudah terbit.')) return; void onSave({ institution: String(form.get('institution')), logoUrl: String(form.get('logoUrl')), openingTime: String(form.get('openingTime')), closingTime: String(form.get('closingTime')), dailyLimit: Number(form.get('dailyLimit')), enabled }); }}><label className="field">Nama instansi<input name="institution" defaultValue={initial.institution} required minLength={2} maxLength={100}/></label><label className="field">URL logo <span className="optional">Opsional</span><input name="logoUrl" defaultValue={initial.logoUrl} placeholder="https://instansi.example/logo.png atau /logo.png" maxLength={1000}/></label><div className="two-fields"><label className="field">Jam buka (WIB)<input type="time" name="openingTime" defaultValue={initial.openingTime} required/></label><label className="field">Jam tutup (WIB)<input type="time" name="closingTime" defaultValue={initial.closingTime} required/></label></div><label className="field">Batas total antrian per hari<input type="number" name="dailyLimit" min={1} max={10000} defaultValue={initial.dailyLimit} required/></label><label className="checkbox-field"><input type="checkbox" name="enabled" defaultChecked={initial.enabled}/>Buka pengambilan nomor sesuai jam pelayanan</label><p className="muted">Berlaku setiap hari dalam zona waktu Asia/Jakarta. Nomor dimulai dari 001 pada tanggal baru tanpa menghapus riwayat.</p><Submit busy={busy}><Save size={18}/>Simpan pengaturan</Submit></form></section>;
}
